name: Tests

on:
  push:
    branches: [master, 7.x]
  pull_request:
    branches: [master, 7.x]

jobs:
  build:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: npm

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run test suite
        run: npm test

      - name: Collect coverage
        run: npm run coverage
